// app/page.tsx — Pulse Department Landing Page
import Link from 'next/link';
import { ArrowRight, Globe, Zap, BarChart3, Users, CheckCircle, TrendingUp, Newspaper, Sparkles } from 'lucide-react';

const VERTICALS = [
  'Business & Management', 'Technology & IT', 'Finance & Investment',
  'Healthcare', 'Marketing & Growth', 'Legal & Compliance',
  'Manufacturing', 'Human Resources', 'Real Estate', 'Agriculture',
];

const FEATURES = [
  {
    icon: Globe,
    title: '70/30 Global + Local',
    desc: 'World-class global intelligence blended with insights specific to your country and market.',
  },
  {
    icon: Zap,
    title: 'Generate On Demand',
    desc: "Fresh magazine issues generated by Claude AI whenever you need them, within your monthly allowance.",
  },
  {
    icon: BarChart3,
    title: '10-Section Magazine Format',
    desc: 'News, trends, case studies, market data, leadership, regulatory updates — all in one structured issue.',
  },
  {
    icon: Users,
    title: 'Multi-Profession Support',
    desc: 'Subscribe to multiple verticals. One dashboard, all your professional worlds.',
  },
  {
    icon: Sparkles,
    title: 'Pulse Lens',
    desc: "Every issue, your lead story gets reframed through a rotating expert lens — Historian, Outsider, Constraint, or Apprentice — for a genuinely fresh angle no generic AI prompt gives you.",
  },
];

const PLANS = [
  {
    name: 'Starter',
    price: '$10',
    period: '/month',
    verticals: '1 vertical',
    features: ['4 issues per month, generate anytime', 'Global, continental & local news', 'Full 10-section magazine format', 'Pulse Lens on every issue', 'Press Clippings — track 1 term', 'Mobile + desktop access'],
    cta: 'View pricing',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$25',
    period: '/month',
    verticals: 'Up to 5 verticals',
    features: ['12 issues per month, generate anytime', 'Up to 5 professional verticals', 'Pulse Lens on every issue', 'Press Clippings — track 3 terms', 'Priority processing', 'Full content history'],
    cta: 'View pricing',
    highlight: true,
  },
  {
    name: 'Corporate',
    price: '$75',
    period: '/month',
    verticals: 'Unlimited verticals',
    features: ['40 issues per month, generate anytime', 'Unlimited verticals', 'Pulse Lens on every issue', 'Press Clippings — track 10 terms', 'Global, continental & local news', 'Priority support'],
    cta: 'View pricing',
    highlight: false,
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="fixed top-0 w-full z-50 bg-white/80 backdrop-blur border-b border-slate-100">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-6 w-6 text-blue-600" />
            <span className="font-bold text-base text-slate-900 whitespace-nowrap">Pulse Department</span>
          </div>
          {/* Nav buttons - all screen sizes */}
          <div className="flex items-center gap-2">
            <Link href="/login" className="text-xs sm:text-sm text-slate-600 hover:text-slate-900 transition-colors px-2 py-1.5 whitespace-nowrap">
              Sign in
            </Link>
            <Link href="/signup" className="text-xs sm:text-sm bg-blue-600 text-white px-3 py-1.5 rounded-lg hover:bg-blue-700 transition-colors whitespace-nowrap">
              Get started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 text-sm font-medium px-4 py-2 rounded-full mb-8">
            <Zap className="h-4 w-4" />
            AI-powered professional intelligence
          </div>
          <h1 className="text-5xl sm:text-6xl font-bold text-slate-900 leading-tight mb-6">
            Your profession,<br />
            <span className="text-blue-600">globally informed.</span>
          </h1>
          <p className="text-xl text-slate-500 max-w-2xl mx-auto mb-6">
            A fresh AI-generated magazine for your profession — 70% global insight, 30% localized to your market.
          </p>
          <Link
            href="#clippings"
            className="inline-flex items-center gap-1.5 mb-8 text-sm font-medium text-slate-600 border border-slate-200 rounded-full px-4 py-2 hover:border-blue-300 hover:text-blue-600 transition-colors"
          >
            <Newspaper className="h-3.5 w-3.5" />
            Plus Press Clippings — weekly briefings on people, companies & topics you track
          </Link>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/signup"
              className="inline-flex items-center justify-center gap-2 bg-blue-600 text-white px-8 py-4 rounded-xl font-semibold hover:bg-blue-700 transition-colors text-lg"
            >
              Try free — 1 issue, no credit card
              <ArrowRight className="h-5 w-5" />
            </Link>
            <Link
              href="#pricing"
              className="inline-flex items-center justify-center gap-2 bg-slate-100 text-slate-700 px-8 py-4 rounded-xl font-semibold hover:bg-slate-200 transition-colors text-lg"
            >
              View pricing
            </Link>
          </div>
        </div>
      </section>

      {/* Verticals */}
      <section className="py-6 bg-slate-50 border-y border-slate-100 overflow-hidden">
        <div className="flex gap-3 flex-wrap justify-center px-6">
          {VERTICALS.map(v => (
            <span key={v} className="bg-white border border-slate-200 text-slate-600 text-sm px-4 py-2 rounded-full whitespace-nowrap">
              {v}
            </span>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Intelligence that works like you do</h2>
            <p className="text-lg text-slate-500 max-w-xl mx-auto">Built for professionals who need to stay sharp without spending hours reading.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6">
            {FEATURES.map(f => (
              <div key={f.title} className="p-6 rounded-2xl border border-slate-100 hover:border-blue-100 hover:shadow-sm transition-all">
                <div className="w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center mb-4">
                  <f.icon className="h-6 w-6 text-blue-600" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">{f.title}</h3>
                <p className="text-sm text-slate-500">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What's in an issue */}
      <section className="py-24 px-6 bg-slate-50">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Every issue covers 10 sections</h2>
            <p className="text-lg text-slate-500">A complete professional magazine in every generation.</p>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
            {[
              '🎯 Hero Spotlight', '📰 Industry News', '📈 Trends & Analysis',
              '✅ Best Practices', '🏆 Case Studies', '🧠 Leadership',
              '⚖️ Regulatory Updates', '📊 Market Data', '💬 Opinion', '🔗 Resources',
            ].map(s => (
              <div key={s} className="bg-white rounded-xl border border-slate-100 px-4 py-3 text-sm font-medium text-slate-700">
                {s}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Press Clippings */}
      <section id="clippings" className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-12 items-center">
            <div>
              <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 text-sm font-medium px-4 py-2 rounded-full mb-6">
                <Newspaper className="h-4 w-4" />
                Press Clippings
              </div>
              <h2 className="text-3xl font-bold text-slate-900 mb-4">
                Never miss a mention.
              </h2>
              <p className="text-slate-500 mb-6">
                Add people, companies, or topics to your watchlist. Every week, we scan for the latest news on each one and email you a personal briefing — straight to your inbox, no extra dashboard to check.
              </p>
              <Link
                href="/pricing"
                className="inline-flex items-center gap-2 text-blue-600 font-semibold hover:text-blue-700 transition-colors"
              >
                See watchlist limits by plan
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            <div className="bg-slate-50 rounded-2xl border border-slate-100 p-6">
              <div className="flex items-center gap-2 mb-4">
                <Newspaper className="h-4 w-4 text-blue-600" />
                <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Your Press Clippings</span>
              </div>
              <div className="space-y-3">
                <div className="bg-white rounded-xl border-l-3 border-blue-500 px-4 py-3">
                  <p className="text-sm font-semibold text-slate-900">Your tracked term</p>
                  <p className="text-xs text-slate-500 mt-1">Latest headline and a short summary, delivered weekly.</p>
                </div>
                <div className="bg-white rounded-xl border-l-3 border-blue-500 px-4 py-3">
                  <p className="text-sm font-semibold text-slate-900">Another tracked term</p>
                  <p className="text-xs text-slate-500 mt-1">Sourced and summarized automatically.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Simple pricing</h2>
            <p className="text-lg text-slate-500">Start free. Upgrade when you need more verticals and generations.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {PLANS.map(plan => (
              <div
                key={plan.name}
                className={`rounded-2xl p-8 border ${plan.highlight ? 'border-blue-500 bg-blue-600 text-white shadow-xl shadow-blue-200' : 'border-slate-200 bg-white'}`}
              >
                <div className={`text-sm font-semibold mb-2 ${plan.highlight ? 'text-blue-200' : 'text-blue-600'}`}>{plan.name}</div>
                <div className="mb-1">
                  <span className="text-4xl font-bold">{plan.price}</span>
                  <span className={`text-sm ${plan.highlight ? 'text-blue-200' : 'text-slate-500'}`}>{plan.period}</span>
                </div>
                <div className={`text-sm mb-6 ${plan.highlight ? 'text-blue-100' : 'text-slate-500'}`}>{plan.verticals}</div>
                <ul className="space-y-3 mb-8">
                  {plan.features.map(f => (
                    <li key={f} className="flex items-start gap-2 text-sm">
                      <CheckCircle className={`h-4 w-4 mt-0.5 flex-shrink-0 ${plan.highlight ? 'text-blue-200' : 'text-green-500'}`} />
                      <span className={plan.highlight ? 'text-blue-50' : 'text-slate-600'}>{f}</span>
                    </li>
                  ))}
                </ul>
                <Link
                  href="/pricing"
                  className={`block text-center py-3 rounded-xl font-semibold transition-colors ${
                    plan.highlight
                      ? 'bg-white text-blue-600 hover:bg-blue-50'
                      : 'bg-blue-600 text-white hover:bg-blue-700'
                  }`}
                >
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Install app strip */}
      <section className="py-12 px-6 bg-blue-50">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-center justify-center gap-3 text-center sm:text-left">
          <p className="text-sm text-blue-700">
            <span className="font-semibold">Tip:</span> install Pulse Department on your phone for one-tap access — no app store needed.
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-100 py-12 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-blue-600" />
            <span className="font-semibold text-sm text-slate-900 whitespace-nowrap">Pulse Department</span>
          </div>
          <p className="text-sm text-slate-400">© {new Date().getFullYear()} Pulse Department. Professional intelligence, globally sourced.</p>
        </div>
      </footer>
    </div>
  );
}
