// app/page.tsx — Pulse Department Landing Page
import Link from 'next/link';
import { ArrowRight, Globe, Zap, BarChart3, Users, CheckCircle, TrendingUp } from 'lucide-react';

const VERTICALS = [
  'Business & Management', 'Technology & IT', 'Finance & Investment',
  'Healthcare', 'Marketing & Growth', 'Legal & Compliance',
  'Manufacturing', 'Human Resources', 'Real Estate', 'Agriculture',
];

const FEATURES = [
  {
    icon: Globe,
    title: '70/30 Global + Local',
    desc: 'World-class global intelligence blended with insights specific to your country and market.',
  },
  {
    icon: Zap,
    title: 'AI-Generated, Daily',
    desc: "Fresh magazine issues generated by Claude AI every day. Never read yesterday's news twice.",
  },
  {
    icon: BarChart3,
    title: '10-Section Magazine Format',
    desc: 'News, trends, case studies, market data, leadership, regulatory updates — all in one structured issue.',
  },
  {
    icon: Users,
    title: 'Multi-Profession Support',
    desc: 'Subscribe to multiple verticals. One dashboard, all your professional worlds.',
  },
];

const PLANS = [
  {
    name: 'Starter',
    price: '$5',
    period: '/month',
    verticals: '1 vertical',
    features: ['Daily AI magazine issues', '70/30 global + local content', 'Full 10-section format', 'Mobile + desktop'],
    cta: 'Get started free',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '$10',
    period: '/month',
    verticals: 'Up to 5 verticals',
    features: ['Everything in Starter', '3 generations/day', 'Content history 30 days', 'Priority processing'],
    cta: 'Get started free',
    highlight: true,
  },
  {
    name: 'Corporate',
    price: '$20',
    period: '/month',
    verticals: 'Unlimited verticals',
    features: ['Everything in Pro', '10 generations/day', 'Team sharing (5 seats)', 'API access'],
    cta: 'Get started free',
    highlight: false,
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="fixed top-0 w-full z-50 bg-white/80 backdrop-blur border-b border-slate-100">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-6 w-6 text-blue-600" />
            <span className="font-bold text-base text-slate-900 whitespace-nowrap">Pulse Department</span>
          </div>
          {/* Nav buttons - all screen sizes */}
          <div className="flex items-center gap-2">
            <Link href="/login" className="text-xs sm:text-sm text-slate-600 hover:text-slate-900 transition-colors px-2 py-1.5 whitespace-nowrap">
              Sign in
            </Link>
            <Link href="/signup" className="text-xs sm:text-sm bg-blue-600 text-white px-3 py-1.5 rounded-lg hover:bg-blue-700 transition-colors whitespace-nowrap">
              Get started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 text-sm font-medium px-4 py-2 rounded-full mb-8">
            <Zap className="h-4 w-4" />
            AI-powered professional intelligence
          </div>
          <h1 className="text-5xl sm:text-6xl font-bold text-slate-900 leading-tight mb-6">
            Your profession,<br />
            <span className="text-blue-600">globally informed.</span>
          </h1>
          <p className="text-xl text-slate-500 max-w-2xl mx-auto mb-10">
            Up-to-date profession news, topical issues and expert opinions — delivered as a fresh AI-generated magazine. One subscription, any profession, any country. 70% world-class global insights, 30% localized to your market.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/signup"
              className="inline-flex items-center justify-center gap-2 bg-blue-600 text-white px-8 py-4 rounded-xl font-semibold hover:bg-blue-700 transition-colors text-lg"
            >
              Try free — 3 issues, no credit card
              <ArrowRight className="h-5 w-5" />
            </Link>
            <Link
              href="#pricing"
              className="inline-flex items-center justify-center gap-2 bg-slate-100 text-slate-700 px-8 py-4 rounded-xl font-semibold hover:bg-slate-200 transition-colors text-lg"
            >
              View pricing
            </Link>
          </div>
        </div>
      </section>

      {/* Verticals */}
      <section className="py-6 bg-slate-50 border-y border-slate-100 overflow-hidden">
        <div className="flex gap-3 flex-wrap justify-center px-6">
          {VERTICALS.map(v => (
            <span key={v} className="bg-white border border-slate-200 text-slate-600 text-sm px-4 py-2 rounded-full whitespace-nowrap">
              {v}
            </span>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Intelligence that works like you do</h2>
            <p className="text-lg text-slate-500 max-w-xl mx-auto">Built for professionals who need to stay sharp without spending hours reading.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {FEATURES.map(f => (
              <div key={f.title} className="p-6 rounded-2xl border border-slate-100 hover:border-blue-100 hover:shadow-sm transition-all">
                <div className="w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center mb-4">
                  <f.icon className="h-6 w-6 text-blue-600" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">{f.title}</h3>
                <p className="text-sm text-slate-500">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What's in an issue */}
      <section className="py-24 px-6 bg-slate-50">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Every issue covers 10 sections</h2>
            <p className="text-lg text-slate-500">A complete professional magazine in every generation.</p>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
            {[
              '🎯 Hero Spotlight', '📰 Industry News', '📈 Trends & Analysis',
              '✅ Best Practices', '🏆 Case Studies', '🧠 Leadership',
              '⚖️ Regulatory Updates', '📊 Market Data', '💬 Opinion', '🔗 Resources',
            ].map(s => (
              <div key={s} className="bg-white rounded-xl border border-slate-100 px-4 py-3 text-sm font-medium text-slate-700">
                {s}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Simple pricing</h2>
            <p className="text-lg text-slate-500">Start free. Upgrade when you need more verticals.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {PLANS.map(plan => (
              <div
                key={plan.name}
                className={`rounded-2xl p-8 border ${plan.highlight ? 'border-blue-500 bg-blue-600 text-white shadow-xl shadow-blue-200' : 'border-slate-200 bg-white'}`}
              >
                <div className={`text-sm font-semibold mb-2 ${plan.highlight ? 'text-blue-200' : 'text-blue-600'}`}>{plan.name}</div>
                <div className="mb-1">
                  <span className="text-4xl font-bold">{plan.price}</span>
                  <span className={`text-sm ${plan.highlight ? 'text-blue-200' : 'text-slate-500'}`}>{plan.period}</span>
                </div>
                <div className={`text-sm mb-6 ${plan.highlight ? 'text-blue-100' : 'text-slate-500'}`}>{plan.verticals}</div>
                <ul className="space-y-3 mb-8">
                  {plan.features.map(f => (
                    <li key={f} className="flex items-start gap-2 text-sm">
                      <CheckCircle className={`h-4 w-4 mt-0.5 flex-shrink-0 ${plan.highlight ? 'text-blue-200' : 'text-green-500'}`} />
                      <span className={plan.highlight ? 'text-blue-50' : 'text-slate-600'}>{f}</span>
                    </li>
                  ))}
                </ul>
                <Link
                  href={plan.name === 'Starter' ? '/signup' : '/pricing'}
                  className={`block text-center py-3 rounded-xl font-semibold transition-colors ${
                    plan.highlight
                      ? 'bg-white text-blue-600 hover:bg-blue-50'
                      : 'bg-blue-600 text-white hover:bg-blue-700'
                  }`}
                >
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-100 py-12 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-blue-600" />
            <span className="font-semibold text-sm text-slate-900 whitespace-nowrap">Pulse Department</span>
          </div>
          <p className="text-sm text-slate-400">© {new Date().getFullYear()} Pulse Department. Professional intelligence, globally sourced.</p>
        </div>
      </footer>
    </div>
  );
}

